apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-deployment
  namespace: static
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 426520945275.dkr.ecr.us-east-2.amazonaws.com/static:latest
        ports:
        - containerPort: 80
